### ISSUE TITLE
Enquiry button, enquiry form, success page and contact details/footer.

### ISSUE THREAD

**Issue by Chandni-L5** [Chandni-L5/love-running#2]
**User story**
As a former customer, I want to quickly place an enquiry, to be able to get in touch with the service provider asap. 

**Acceptance Criteria**
- [ ] A quick and easy way to access the separate enquiry page.
- [ ] Contact information displayed on every page in the footer. 
- [ ] Separate confirmation page for the enquiry submission.
- [ ] Enquiry form contains all the necessary fields: name, email, phone number, dog name, dog age, services choice, enquiry details, submit button.
- [ ] all fields must be completed before the form can be submitted.

**Tasks**
- [ ] Various enquiry buttons placed strategically throughout the page linking to the enquiry form page. 
- [ ] contact details placed in the footer of every page. 
- [ ] when selecting submit on the enquiry form you are linked through the success page which confirms someone will correspond and if there is urgency the contact details are provided again.
- [ ] Implement a booking inquiry form on the website.
