### ISSUE TITLE
High quality images and engaging testimonials

### ISSUE THREAD

**Issue by Chandni-L5** [Chandni-L5/love-running#3]
**User Story**
As a potential client, I want to read testimonials from previous clients, see high quality images, so that I can feel confident booking with you. 

**Acceptance Criteria**
- [x] The homepage features high-quality images of the dog clients and written feedback.
- [x] Engaging descriptions of the available services are displayed clearly and concisely within the site's content.
- [x] The homepage layout prominently features the images and descriptions in an uncluttered manner.

**Tasks**
- [x] Integrate provided high-quality images of the dog clients into the website and include a text box with the feedback to caption each image and also below the first h1.
