### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Chandni-L5** [Chandni-L5/love-running#4]
**User story**
As a potential client living in a remote location, I want to see what area’s you cover, so that I can decide if I want to book. 

**Acceptance Criteria**
- [ ] The website contains a section covering a list of the area's covered.
- [ ] A map/image showing the locations covered. 

**Tasks**
- [ ] Design and place a section for a list of areas covered. 
- [ ] Design and place a section of a map or image of the locations or town where the service provider is based.
