### ISSUE TITLE
About me

### ISSUE THREAD

**Issue by Chandni-L5** [Chandni-L5/love-running#7]
**User Story**
As a potential client, I would like to see biography of the service provider, to help decide if we would be a good match. 

**Acceptance Criteria**
- [x] The site should contain a section with a short paragraph with a biography.

**Tasks**
- [x] Short text box containing a bio 
- [x] use some icons with short snappy statements of some of the pro's.
